from pydantic import BaseModel, Field
from typing import Literal

class Concept(BaseModel): # Main concept and related connections / Lauri
    id: str
    name: str
    description: str
    prerequisites: list[str] = [] # Pre required concepts

class QuizQuestion(BaseModel): # Quizz question format / Fei
    id: str
    concept_id: str
    question:  str # "Diffrentiate sin(x^2)"
    answer: str # 2*x*cos(x**2)"  (SymPy-parseable)
    difficulty: int = Field(ge=1, le=3)
    
class ConceptProgress(BaseModel): # Users status with any concept
    concept_id: str
    status: Literal["known", "missing", "untested"] = "untested"
    quiz_scores: list[bool] = []
    
class RagChunk(BaseModel): # One retrieved textbook passage / Lauri
    id: str  # chunk id, for citing
    concept_id: str
    text: str # Markdown + LaTeX, formulas inline
    book: str # "Caulus"
    section: str # "3.6 The Chain Rule"
    score: float # how relevant retrueval tought it was
    
class Lesson(BaseModel):
    concept_id: str
    content: str # Markdown + LaTeX, generated by local model
    source_chunk_ids: list[str] = [] # which RAGChunks it was built from
    verified: bool = False # After verification by AI from heaven
    
class VerifierResult(BaseModel): # Verifier result / Fei
    passed: bool
    issues: list[str] = []
    corrected_content: str | None = None